# Generated by Django 4.0.4 on 2022-05-29 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_vehicle_vehicletype'),
    ]

    operations = [
        migrations.AddField(
            model_name='furniture',
            name='current_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='furniture',
            name='depreciation_rate',
            field=models.DecimalField(decimal_places=2, default=0.25, max_digits=4),
        ),
        migrations.AddField(
            model_name='furniture',
            name='initial_value',
            field=models.IntegerField(default=0),
        ),
    ]
