# Generated by Django 4.0.4 on 2022-05-30 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_furniture_current_value_furniture_depreciation_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furniture',
            name='depreciation_rate',
            field=models.IntegerField(),
        ),
    ]
