# Generated by Django 4.0.4 on 2022-05-30 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0004_alter_furniture_depreciation_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furniture',
            name='current_value',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='initial_value',
            field=models.IntegerField(),
        ),
    ]
