# Generated by Django 4.0.4 on 2022-05-30 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0005_alter_furniture_current_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furniture',
            name='depreciation_rate',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
    ]
