# Generated by Django 4.0.4 on 2022-05-31 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0006_alter_furniture_depreciation_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='current_value',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='depreciation_rate',
            field=models.DecimalField(decimal_places=2, max_digits=100, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='initial_value',
            field=models.IntegerField(null=True),
        ),
    ]
