# Generated by Django 4.0.4 on 2022-05-31 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0008_vehicle_custom_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='custom_id',
        ),
    ]
