# Generated by Django 4.0.4 on 2022-06-02 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0009_remove_vehicle_custom_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
