# Generated by Django 4.0.4 on 2022-06-02 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0010_vehicle_time_alter_vehicle_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furniture',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
