# Generated by Django 4.0.4 on 2022-06-04 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0015_alter_furniture_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furniture',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.furnituretype'),
        ),
    ]
