# Generated by Django 4.0.4 on 2022-06-05 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0018_alter_vehicle_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectronicType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Electronic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('initial_value', models.IntegerField(null=True)),
                ('depreciation_rate', models.DecimalField(decimal_places=2, max_digits=100, null=True)),
                ('current_value', models.IntegerField(null=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.electronictype')),
            ],
        ),
    ]
