# Generated by Django 4.0.4 on 2022-06-06 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0019_electronictype_electronic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electronic',
            name='initial_value',
            field=models.IntegerField(),
        ),
    ]
