# Generated by Django 4.0.4 on 2022-06-06 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0021_alter_electronic_date_alter_electronic_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electronic',
            name='id',
        ),
        migrations.AlterField(
            model_name='electronic',
            name='serial_number',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
